### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by hacktolove** [tiendc/sqlboiler-extensions-demo#4]
Hi there! Thanks for the work @tiendc .

I am a newbie to sqlboiler , I’m encountering an installation issue with SQLBoiler while working on my project. I’m not using GOPATH, and I’d like to set up SQLBoiler with Go modules.

How to install the extension ?

Using postgres database . when I run the command :
```
sqlboiler psql -c sqlboiler.toml --wipe --add-global-variants --templates ~/go/pkg/mod/github.com/tiendc/sqlboiler-extensions@v0.8.0/templates
```

I get this error :
```
 "Error: unable to generate output: failed to execute template: main/17_upsert.go.tpl: template: main/17_upsert.go.tpl:40:14: executing "main/17_upsert.go.tpl" at <{{template "timestamp_upsert_helper" .}}>: template "timestamp_upsert_helper" not defined" "
```

Everything works fine without the `--templates` tag.

**Comment by tiendc** [comment]
> Hi there! Thanks for the work @tiendc .
> 
> I am a newbie to sqlboiler , I’m encountering an installation issue with SQLBoiler while working on my project. I’m not using GOPATH, and I’d like to set up SQLBoiler with Go modules.
> 
> How to install the extension ?
> 
> Using postgres database . when I run the command :
> 
> ```
> sqlboiler psql -c sqlboiler.toml --wipe --add-global-variants --templates ~/go/pkg/mod/github.com/tiendc/sqlboiler-extensions@v0.8.0/templates
> ```
> 
> I get this error :
> 
> ```
>  "Error: unable to generate output: failed to execute template: main/17_upsert.go.tpl: template: main/17_upsert.go.tpl:40:14: executing "main/17_upsert.go.tpl" at <{{template "timestamp_upsert_helper" .}}>: template "timestamp_upsert_helper" not defined" "
> ```
> 
> Everything works fine without the `--templates` tag.

I think you need to pass both the main templates and the extension part like:

```shell
sqlboiler psql -c db/sqlboiler.toml \
 		--templates $(GOPATH)/pkg/mod/github.com/volatiletech/sqlboiler/v4@$(BOIL_VER)/templates/main \
 		--templates $(GOPATH)/pkg/mod/github.com/tiendc/sqlboiler-extensions@$(BOIL_EXT_VER)/templates/boilv4/postgres
```

Use your correct paths and verisons of sqlboiler and sqlboiler-extensions.

**Comment by ISNewton** [comment]
Passing the main templates before the extension templates solved my problem !.

But I can not see the extension `modelSlice.InsertAll()` method ? 
![image](https://github.com/tiendc/sqlboiler-extensions-demo/assets/87209980/8cac851c-fa55-4eff-8eb6-561fc67d893b)

**Comment by hacktolove** [comment]
Passing the main templates before the extension templates solved my problem !.
Thanks for the help @tiendc  :1st_place_medal:
